"""initial schema

Revision ID: 20260719_0001
Revises:
Create Date: 2026-07-19 20:09:23.779790
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "20260719_0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_organizations_code"), "organizations", ["code"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "ADMIN", "COUNSELOR", "PSYCHOLOGIST", name="userrole", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=64), nullable=True),
        sa.Column("summary", sa.String(length=500), nullable=False),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("extra_data", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_actor_id"), "audit_logs", ["actor_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_resource_type"), "audit_logs", ["resource_type"], unique=False
    )
    op.create_table(
        "students",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_no", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("gender", sa.String(length=20), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("major", sa.String(length=100), nullable=True),
        sa.Column("grade", sa.String(length=32), nullable=True),
        sa.Column("class_name", sa.String(length=100), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("emergency_contact_name", sa.String(length=100), nullable=True),
        sa.Column("emergency_contact_phone", sa.String(length=32), nullable=True),
        sa.Column("counselor_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["counselor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_students_class_name"), "students", ["class_name"], unique=False)
    op.create_index(op.f("ix_students_counselor_id"), "students", ["counselor_id"], unique=False)
    op.create_index(op.f("ix_students_grade"), "students", ["grade"], unique=False)
    op.create_index(op.f("ix_students_name"), "students", ["name"], unique=False)
    op.create_index(
        op.f("ix_students_organization_id"), "students", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_students_student_no"), "students", ["student_no"], unique=True)
    op.create_table(
        "care_cases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_no", sa.String(length=40), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column(
            "risk_level",
            sa.Enum("GREEN", "YELLOW", "RED", name="risklevel", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "MONITORING",
                "REFERRED",
                "CLOSED",
                name="casestatus",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("issue_tags", sa.JSON(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "confidentiality",
            sa.Enum("NORMAL", "RESTRICTED", name="confidentiality", native_enum=False, length=24),
            nullable=False,
        ),
        sa.Column("next_follow_up_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("close_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_care_cases_case_no"), "care_cases", ["case_no"], unique=True)
    op.create_index(
        op.f("ix_care_cases_next_follow_up_at"), "care_cases", ["next_follow_up_at"], unique=False
    )
    op.create_index(op.f("ix_care_cases_owner_id"), "care_cases", ["owner_id"], unique=False)
    op.create_index(op.f("ix_care_cases_risk_level"), "care_cases", ["risk_level"], unique=False)
    op.create_index(op.f("ix_care_cases_status"), "care_cases", ["status"], unique=False)
    op.create_index(
        "ix_care_cases_status_risk", "care_cases", ["status", "risk_level"], unique=False
    )
    op.create_index(op.f("ix_care_cases_student_id"), "care_cases", ["student_id"], unique=False)
    op.create_index(
        "uq_active_case_per_student",
        "care_cases",
        ["student_id"],
        unique=True,
        postgresql_where=sa.text("status <> 'CLOSED'"),
        sqlite_where=sa.text("status <> 'CLOSED'"),
    )
    op.create_table(
        "followups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PLANNED",
                "COMPLETED",
                "UNREACHABLE",
                "CANCELLED",
                name="followupstatus",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column(
            "method",
            sa.Enum(
                "IN_PERSON",
                "PHONE",
                "MESSAGE",
                "HOME_VISIT",
                "OTHER",
                name="followupmethod",
                native_enum=False,
                length=24,
            ),
            nullable=True,
        ),
        sa.Column(
            "condition",
            sa.Enum(
                "IMPROVED",
                "STABLE",
                "WORSE",
                "UNKNOWN",
                name="studentcondition",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("issue_tags", sa.JSON(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("actions", sa.Text(), nullable=True),
        sa.Column("contact_result", sa.String(length=200), nullable=True),
        sa.Column("next_follow_up_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["care_cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_followups_case_id"), "followups", ["case_id"], unique=False)
    op.create_index(
        op.f("ix_followups_created_by_id"), "followups", ["created_by_id"], unique=False
    )
    op.create_index(op.f("ix_followups_scheduled_at"), "followups", ["scheduled_at"], unique=False)
    op.create_index(op.f("ix_followups_status"), "followups", ["status"], unique=False)
    op.create_index(
        "ix_followups_status_scheduled", "followups", ["status", "scheduled_at"], unique=False
    )
    op.create_table(
        "referrals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("requested_by_id", sa.Integer(), nullable=False),
        sa.Column("assigned_to_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ACCEPTED",
                "COMPLETED",
                "REJECTED",
                name="referralstatus",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("professional_note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["assigned_to_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["case_id"], ["care_cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["requested_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_referrals_assigned_to_id"), "referrals", ["assigned_to_id"], unique=False
    )
    op.create_index(op.f("ix_referrals_case_id"), "referrals", ["case_id"], unique=False)
    op.create_index(
        op.f("ix_referrals_requested_by_id"), "referrals", ["requested_by_id"], unique=False
    )
    op.create_index(op.f("ix_referrals_status"), "referrals", ["status"], unique=False)
    op.create_table(
        "risk_changes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column(
            "from_level",
            sa.Enum("GREEN", "YELLOW", "RED", name="risklevel", native_enum=False, length=16),
            nullable=True,
        ),
        sa.Column(
            "to_level",
            sa.Enum("GREEN", "YELLOW", "RED", name="risklevel", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("changed_by_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["care_cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["changed_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_risk_changes_case_id"), "risk_changes", ["case_id"], unique=False)
    op.create_index(
        op.f("ix_risk_changes_changed_by_id"), "risk_changes", ["changed_by_id"], unique=False
    )
    op.create_index(op.f("ix_risk_changes_to_level"), "risk_changes", ["to_level"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_risk_changes_to_level"), table_name="risk_changes")
    op.drop_index(op.f("ix_risk_changes_changed_by_id"), table_name="risk_changes")
    op.drop_index(op.f("ix_risk_changes_case_id"), table_name="risk_changes")
    op.drop_table("risk_changes")
    op.drop_index(op.f("ix_referrals_status"), table_name="referrals")
    op.drop_index(op.f("ix_referrals_requested_by_id"), table_name="referrals")
    op.drop_index(op.f("ix_referrals_case_id"), table_name="referrals")
    op.drop_index(op.f("ix_referrals_assigned_to_id"), table_name="referrals")
    op.drop_table("referrals")
    op.drop_index("ix_followups_status_scheduled", table_name="followups")
    op.drop_index(op.f("ix_followups_status"), table_name="followups")
    op.drop_index(op.f("ix_followups_scheduled_at"), table_name="followups")
    op.drop_index(op.f("ix_followups_created_by_id"), table_name="followups")
    op.drop_index(op.f("ix_followups_case_id"), table_name="followups")
    op.drop_table("followups")
    op.drop_index(
        "uq_active_case_per_student",
        table_name="care_cases",
        postgresql_where=sa.text("status <> 'CLOSED'"),
        sqlite_where=sa.text("status <> 'CLOSED'"),
    )
    op.drop_index(op.f("ix_care_cases_student_id"), table_name="care_cases")
    op.drop_index("ix_care_cases_status_risk", table_name="care_cases")
    op.drop_index(op.f("ix_care_cases_status"), table_name="care_cases")
    op.drop_index(op.f("ix_care_cases_risk_level"), table_name="care_cases")
    op.drop_index(op.f("ix_care_cases_owner_id"), table_name="care_cases")
    op.drop_index(op.f("ix_care_cases_next_follow_up_at"), table_name="care_cases")
    op.drop_index(op.f("ix_care_cases_case_no"), table_name="care_cases")
    op.drop_table("care_cases")
    op.drop_index(op.f("ix_students_student_no"), table_name="students")
    op.drop_index(op.f("ix_students_organization_id"), table_name="students")
    op.drop_index(op.f("ix_students_name"), table_name="students")
    op.drop_index(op.f("ix_students_grade"), table_name="students")
    op.drop_index(op.f("ix_students_counselor_id"), table_name="students")
    op.drop_index(op.f("ix_students_class_name"), table_name="students")
    op.drop_table("students")
    op.drop_index(op.f("ix_audit_logs_resource_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_organizations_code"), table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
